[platformio]
default_envs = native_ref

[env:native_ref]
platform = native
build_flags =
  -std=gnu++17
  -Iinclude

[env:at32f403avct7]
platform = https://github.com/ArteryTek/platform-arterytekat32.git
board = AT32F403AVCT7
framework = cmsis
build_src_filter =
  -<src/main.cpp>
  +<at32/src/*.c>
  +<at32/startup/*.S>
build_flags =
  -Iat32/include
  -ffreestanding
  -fdata-sections
  -ffunction-sections
board_build.ldscript = at32/linker_at32f403avct7.ld
